load: load.c
	gcc load.c -o load

dump: dump.c load
	gcc dump.c -o dump

sum: sum.c
	gcc sum.c -o sum

sub: sub.c
	gcc sub.c -o sub

flow: flow.c
	gcc flow.c -o flow

loop: loop.c
	gcc loop.c -o loop

seek: seek.c
	gcc seek.c -o seek